# Generated by Django 5.1.2 on 2024-11-06 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restataurant',
            new_name='Restaurant',
        ),
    ]
